FROM python:3.11-bullseye

ENV DEBIAN_FRONTEND=noninteractive

RUN pip install redis watchdog
RUN pip install pydicom

RUN adduser --disabled-password --gecos "" rtfmri
RUN mkdir /mnt/scanner
#RUN chown -R rtfmri:rtfmri /mnt/scanner
RUN mkdir /logs
RUN chown -R rtfmri:rtfmri /logs

#RUN wget -q https://raw.githubusercontent.com/javanile/inotifywait-polling/main/inotifywait-polling.sh && chmod +x /inotifywait-polling.sh
#COPY inotifywait-polling.patch /inotifywait-polling.patch
#RUN patch -p0 /inotifywait-polling.patch && rm /inotifywait-polling.patch

WORKDIR /
ADD run_dicom_detector.sh run_dicom_detector.sh
RUN chmod u+x run_dicom_detector.sh

ADD detect_dicoms.py detect_dicoms.py
CMD ["/run_dicom_detector.sh"]
