version: '3'

services:
  realtimefmri:
    build:
      context: .
      dockerfile: Dockerfile.realtimefmri
    command: web_interface
    devices:
      - "${EVENT_DEVICE}:/dev/input/event3"
    ports:
      - "127.0.0.1:8050:8050"
    volumes:
      - "${PYCORTEX_STORE}:/data/pycortex_store"
      - "${PIPELINE_PATH}:/root/.local/share/realtimefmri/pipelines"
      - "${TEST_DATASET_PATH}:/root/.local/share/realtimefmri/datasets/test_dataset"
    restart: always

  redis:
    image: redis
    restart: always
