version: '3'

services:
  realtimefmri:
    build:
      context: .
      dockerfile: Dockerfile.realtimefmri
    command: web_interface
    devices:
      - "/dev/input/event3:/dev/input/event3"
    ports:
      - "127.0.0.1:8050:8050"

  redis:
    image: redis
