version: '3'

services:
  realtimefmri:
    build:
      context: .
      dockerfile: Dockerfile
    command: web_interface
    depends_on:
      - redis
      - samba
    devices:
      - "${EVENT_DEVICE}:/dev/input/event3"
    environment:
      - REALTIMEFMRI_LOG_LEVEL=${LOG_LEVEL}
    ports:
      - "127.0.0.1:8050:8050"
      - "127.0.0.1:8051:8051"
    restart: always
    volumes:
      - "${PYCORTEX_STORE}:/usr/local/share/pycortex/db"
      - "${PIPELINE_DIR}:/usr/local/share/realtimefmri/pipelines"
      - "${EXPERIMENT_DIR}:/usr/local/share/realtimefmri/experiments"
      - "${DATASTORE_DIR}:/usr/local/share/realtimefmri/datastore"
      - "${TEST_DATASET_DIR}:/usr/local/share/realtimefmri/datasets"
      - "${LOG_DIR}:/usr/local/share/realtimefmri/logs"
      - "${STATIC_PATH}:/public/static"
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - scanner:/usr/local/share/realtimefmri/scanner
      - .:/app/realtimefmri

  redis:
    image: redis
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime

  samba:
    build:
      context: "./samba"
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:139:139"
      - "0.0.0.0:445:445"
    restart: always
    volumes:
      - scanner:/mnt/scanner
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - "${LOG_DIR}:/logs"

volumes:
  scanner:
