global_parameters:
  n_skip: 0

pipeline:
  - name: debug
    class_name: realtimefmri.preprocess.Debug
    input: [ raw_image_nii ]
    output: [ nii_repr, nii_shape ]

  - name: motion_correct
    class_name: realtimefmri.preprocess.MotionCorrect
    kwargs: { surface: RGfs, transform: 20170705RG_movies, mask_type: thick }
    input: [ raw_image_nii ]
    output: [ image_nifti_mc ]

  - name: nifti_to_volume
    class_name: realtimefmri.preprocess.NiftiToVolume
    input: [ image_nifti_mc ]
    output: [ volume ]

  - name: gm_mask
    class_name: realtimefmri.preprocess.ApplyMask
    kwargs: { surface: RGfs, transform: 20170705RG_movies, mask_type: thick }
    input: [ volume ]
    output: [ gm_responses ]

  - name: incremental_mean_std
    class_name: realtimefmri.preprocess.IncrementalMeanStd
    input: [ gm_responses ]
    output: [ gm_mean, gm_std ]

  - name: zscore
    class_name: realtimefmri.preprocess.ZScore
    input: [ gm_responses, gm_mean, gm_std ]
    output: [ gm_zscore ]

  - name: volume_to_mosaic
    class_name: realtimefmri.preprocess.VolumeToMosaic
    input: [ volume ]
    output: [ volume_mosaic ]

  - name: send_mosaic
    class_name: realtimefmri.stimulate.SendToDashboard
    kwargs: { name: mosaic, plot_type: array_image }
    input: [ volume_mosaic ]

  - name: array_mean
    class_name: realtimefmri.preprocess.ArrayMean
    kwargs: { dimensions: [0]}
    input: [ gm_responses ]
    output: [ gm_grand_mean ]

  - name: send_gm
    class_name: realtimefmri.stimulate.SendToDashboard
    kwargs: { name: gm_mean, plot_type: timeseries }
    input: [ gm_grand_mean ]

  - name: flatmap
    class_name: realtimefmri.stimulate.SendToPycortexViewer
    kwargs: { name: flatmap }
    input: [ gm_zscore ]
