global_parameters:
  n_skip: 0

pipeline:
  - name: debug
    class_name: realtimefmri.preprocess.Debug
    input: [ raw_image_nii ]
    output: [ nii_repr, nii_shape ]

  - name: motion_correct
    class_name: realtimefmri.preprocess.MotionCorrect
    kwargs: { surface: RGfs, transform: 20170705RG_movies, mask_type: thick }
    input: [ raw_image_nii ]
    output: [ image_nifti_mc ]

  - name: nifti_to_volume
    class_name: realtimefmri.preprocess.NiftiToVolume
    input: [ image_nifti_mc ]
    output: [ volume ]

  - name: gm_mask
    class_name: realtimefmri.preprocess.ApplyMask
    kwargs: { surface: RGfs, transform: 20170705RG_movies, mask_type: thick }
    input: [ volume ]
    output: [ gm_responses ]

  - name: flatmap
    class_name: realtimefmri.stimulate.SendToPycortexViewer
    kwargs: { name: flatmap }
    input: [ gm_responses ]
