global_parameters:
  recording_id: &RECORDING_ID example

pipeline:
  - name: debug
    step: realtimefmri.stimulate.Debug
    topic: { raw_image_nii: data }
  - name: send_to_dashboard 
    step: realtimefmri.stimulate.SendToDashboard
    topic: {volume_name: name, volume_data: data}
