global_defaults:
  subject: &SUBJECT TZfs2
  xfm_name: &XFMNAME controller_test_20161026TZ2
  nskip: 5

pipeline:
  - name: raw_to_nifti
    instance: !!python/object:realtimefmri.preprocessing.RawToNifti {}
    input: [ raw_image_binary ]
    output: [ image_nifti ]

  - name: motion_correct
    instance: !!python/object:realtimefmri.preprocessing.MotionCorrect {}
    input: [ image_nifti ]
    output: [ image_nifti_mc ]
  
  - name: save_nifti
    instance: !!python/object:realtimefmri.preprocessing.SaveNifti {}
    input: [ image_nifti_mc ]

  - name: extract_gm_mask
    instance: !!python/object:realtimefmri.preprocessing.ApplyMask {}
    kwargs: { mask_type: thick }
    input: [ image_nifti_mc ]
    output: [ gm_activity ]

  - name: running_mean_std
    instance: !!python/object:realtimefmri.preprocessing.OnlineMoments {}
    input: [ gm_activity ]
    output:
      - gm_activity_mean
      - gm_activity_std

  - name: gm_activity_zscore
    instance: !!python/object:realtimefmri.preprocessing.VoxelZScore {}
    input:
      - gm_activity
      - gm_activity_mean
      - gm_activity_std
    output: [ gm_activity_zscore ]
    send: [ gm_activity_zscore ]
