global_defaults:
  subject: &SUBJECT TZfs
  xfm_name: &XFMNAME driving_20170704TZ
  nskip: 0

pipeline:
  - name: dicom_to_nifti
    instance: !!python/object:realtimefmri.preprocess.DicomToNifti {}
    input: [ raw_image_binary ]
    output: [ image_nifti ]

  - name: motion_correct
    instance: !!python/object:realtimefmri.preprocess.MotionCorrect {}
    input: [ image_nifti ]
    output: [ image_nifti_mc ]

  - name: save_nifti
    instance: !!python/object:realtimefmri.preprocess.SaveNifti {}
    input:
      - image_nifti_mc
      - image_id
  
  - name: extract_gm_mask
    instance: !!python/object:realtimefmri.preprocess.ApplyMask {}
    kwargs: { mask_type: thick }
    input: [ image_nifti ]
    output: [ gm_activity ]

  - name: running_mean_std
    instance: !!python/object:realtimefmri.preprocess.RunningMeanStd {}
    input:
      - gm_activity
      - image_id
    output:
      - gm_activity_mean
      - gm_activity_std

  - name: gm_activity_zscore
    instance: !!python/object:realtimefmri.preprocess.VoxelZScore {}
    input:
      - gm_activity
      - gm_activity_mean
      - gm_activity_std
    output: [ gm_activity_zscore ]
    send: [ gm_activity_zscore ]
