global_defaults:
  subject: &SUBJECT TZfs2
  xfm_name: &XFMNAME controller_test_20161026TZ2
  nskip: 3

pipeline:
  - name: raw_to_nifti
    instance: !!python/object:realtimefmri.preprocess.RawToNifti {}
    input: [ raw_image_binary ]
    output: [ image_nifti ]

  - name: motion_correct
    instance: !!python/object:realtimefmri.preprocess.MotionCorrect {}
    kwargs : { twopass: true }
    input: [ image_nifti ]
    output: [ image_nifti_mc ]
  
  - name: extract_gm_mask
    instance: !!python/object:realtimefmri.preprocess.ApplyMask {}
    kwargs: { mask_type: thick }
    input: [ image_nifti ]
    output: [ gm_activity ]

  - name: online_moments
    instance: !!python/object:realtimefmri.preprocess.OnlineMoments {}
    input: [ gm_activity ]
    output:
      - gm_activity_mean
      - gm_activity_std

  - name: gm_activity_zscore
    instance: !!python/object:realtimefmri.preprocess.VoxelZScore {}
    input:
      - gm_activity
      - gm_activity_mean
      - gm_activity_std
    output: [ gm_activity_zscore ]
    send: [ gm_activity_zscore ]
